-- +goose Up
-- +goose StatementBegin

-- ---------- ENUMS ------------------
CREATE TYPE enm_users_type AS ENUM ('seller', 'user', 'admin');

-- ---------- TABLE USERS -----------
CREATE TABLE IF NOT EXISTS users (
  uid         int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name        text NOT NULL,
  email       text NOT NULL,
  password    text NOT NULL,
  type        enm_users_type NOT NULL DEFAULT 'user',
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_users PRIMARY KEY (uid),
  CONSTRAINT uq_users_email UNIQUE (email)
);

-- ---------- TABLE PRODUCT -----------
CREATE TABLE IF NOT EXISTS product (
  pid         int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pname       text NOT NULL,
  preview     text,
  path        text,
  seller_id   int NOT NULL,
  price       int NOT NULL,
  discount    int,
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_product PRIMARY KEY (pid),
  CONSTRAINT fk_product_seller FOREIGN KEY (seller_id) REFERENCES users(uid)
);

CREATE INDEX idx_product_seller_id ON product (seller_id);

-- ---------- TABLE SALES -----------
CREATE TABLE IF NOT EXISTS sales (
  sid         int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pid         int NOT NULL,
  uid         int NOT NULL,
  is_paid     boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_sales PRIMARY KEY (sid),
  CONSTRAINT fk_sales_pid FOREIGN KEY (pid) REFERENCES product(pid),
  CONSTRAINT fk_sales_uid FOREIGN KEY (uid) REFERENCES users(uid)
);

CREATE INDEX idx_sales_pid ON sales (pid);
CREATE INDEX idx_sales_uid ON sales (uid);

-- ---------- TABLE REVIEWS -----------
CREATE TABLE IF NOT EXISTS reviews (
  rid         int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  sid         int NOT NULL,
  message     text,
  stars       int,
  created_at  timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT pk_reviews PRIMARY KEY (rid),
  CONSTRAINT fk_reviews_sid FOREIGN KEY (sid) REFERENCES sales(sid),
  CONSTRAINT chk_reviews_stars CHECK (stars BETWEEN 1 AND 5)
);

CREATE INDEX idx_reviews_sid ON reviews (sid);

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS enm_users_type;

-- +goose StatementEnd
