// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const emailTaken = `-- name: EmailTaken :one
SELECT EXISTS ( SELECT 1 FROM users WHERE email = $1 ) AS found
`

func (q *Queries) EmailTaken(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailTaken, email)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const exists = `-- name: Exists :one
SELECT EXISTS (SELECT 1 FROM users WHERE uid = $1 ) AS found
`

func (q *Queries) Exists(ctx context.Context, uid int32) (bool, error) {
	row := q.db.QueryRow(ctx, exists, uid)
	var found bool
	err := row.Scan(&found)
	return found, err
}

const loginUser = `-- name: LoginUser :one
SELECT uid, name, password FROM users WHERE email = $1
`

type LoginUserRow struct {
	Uid      int32
	Name     string
	Password string
}

func (q *Queries) LoginUser(ctx context.Context, email string) (LoginUserRow, error) {
	row := q.db.QueryRow(ctx, loginUser, email)
	var i LoginUserRow
	err := row.Scan(&i.Uid, &i.Name, &i.Password)
	return i, err
}

const signupUser = `-- name: SignupUser :one
INSERT INTO users (name,email,password) VALUES ($1,$2,$3) RETURNING uid
`

type SignupUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) SignupUser(ctx context.Context, arg SignupUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, signupUser, arg.Name, arg.Email, arg.Password)
	var uid int32
	err := row.Scan(&uid)
	return uid, err
}
