// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
)

const signupUser = `-- name: SignupUser :one
INSERT INTO users (name,email,password) VALUES ($1,$2,$3) RETURNING uid
`

type SignupUserParams struct {
	Name     string
	Email    string
	Password string
}

func (q *Queries) SignupUser(ctx context.Context, arg SignupUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, signupUser, arg.Name, arg.Email, arg.Password)
	var uid int32
	err := row.Scan(&uid)
	return uid, err
}
